### ISSUE TITLE
Add constants for "Customising Detail View"

### ISSUE THREAD

**Issue by yjsoon** [tinkercademy/Swift-Tutorials#1]
In "Customising Detail View", let's use constants for the profile picture size

![Screencap from video](https://user-images.githubusercontent.com/126824/124538599-7fed3700-de4e-11eb-865c-b92f43cdb72d.png)

**Comment by jiachenyee** [comment]
Shouldn't the `profilePicSize` be declared within the scope of the `FriendDetailView` so it's not a global variable?

**Comment by yjsoon** [comment]
Oh yeah that works
